{{- if .Values.restdefinitions.runnergroup.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-runnergroup
data:
  runnergroup.yaml: |
{{ tpl (.Files.Get "assets/runnergroup.yaml") . | indent 4 }}
{{ end }}
