{{- if .Values.restdefinitions.workflow.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-workflow
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-delete
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  workflow.yaml: |
{{ tpl (.Files.Get "assets/workflow.yaml") . | indent 4 }}
{{ end }}
