{{- if .Values.restdefinitions.runnergroup.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-runnergroup
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-delete
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  runnergroup.yaml: |
{{ tpl (.Files.Get "assets/runnergroup.yaml") . | indent 4 }}
{{ end }}
