{{- if .Values.restdefinitions.collaborator.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-collaborator
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-delete
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  collaborator.yaml: |
{{ tpl (.Files.Get "assets/collaborator.yaml") . | indent 4 }}
{{ end }}
  