apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-plugin-krateo
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-plugin-krateo
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-plugin-krateo
    spec:
      containers:
        - name: {{ .Release.Name }}-plugin-krateo
          #image: ghcr.io/krateoplatformops/github-rest-dynamic-controller-plugin:{{ .Values.webservice.image.tag }}
          image: {{ .Values.webservice.image.repository }}:{{ .Values.webservice.image.tag }}
          imagePullPolicy: {{ .Values.webservice.image.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.webservice.image.ports.containerPort }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 5
