{{- if .Values.restdefinitions.collaborator.enabled }}
kind: RestDefinition
apiVersion: ogen.krateo.io/v1alpha1
metadata:
  name: {{ .Release.Name }}-collaborator
spec:
  oasPath: configmap://{{ .Release.Namespace }}/{{ .Release.Name }}-collaborator/collaborator.yaml
  resourceGroup: github.ogen.krateo.io
  resource: 
    kind: Collaborator
    additionalStatusFields:
      - id
      - html_url
      - permissions
      - message
    verbsDescription:
    - action: create
      method: POST
      path: /repository/{owner}/{repo}/collaborators/{username}            # plugin endpoint
    - action: delete
      method: DELETE
      path: /repository/{owner}/{repo}/collaborators/{username}            # plugin endpoint
    - action: get
      method: GET
      path: /repository/{owner}/{repo}/collaborators/{username}/permission # plugin endpoint
    - action: update
      method: PATCH
      path: /repository/{owner}/{repo}/collaborators/{username}            # plugin endpoint
{{ end }}
