{{- if .Values.restdefinitions.collaborator.enabled }}
kind: RestDefinition
apiVersion: swaggergen.krateo.io/v1alpha1
metadata:
  name: {{ .Release.Name }}-collaborator
spec:
  oasPath: configmap://{{ .Release.Namespace }}/{{ .Release.Name }}-collaborator/collaborator.yaml
  resourceGroup: github.kog.krateo.io
  resource: 
    kind: Collaborator
    identifiers:
      - id
      - permissions
      - html_url
      - message
    verbsDescription:
    - action: create
      method: POST
      path: /repository/{owner}/{repo}/collaborators/{username}
    - action: delete
      method: DELETE
      path: /repository/{owner}/{repo}/collaborators/{username}
    - action: get
      method: GET
      path: /repository/{owner}/{repo}/collaborators/{username}/permission
    - action: update
      method: PATCH
      path: /repository/{owner}/{repo}/collaborators/{username}
{{ end }}
