{{- if .Values.restdefinitions.runnergroup.enabled }}
kind: RestDefinition
apiVersion: ogen.krateo.io/v1alpha1
metadata:
  name: {{ .Release.Name }}-runnergroup
spec:
  oasPath: configmap://{{ .Release.Namespace }}/{{ .Release.Name }}-runnergroup/runnergroup.yaml
  resourceGroup: github.ogen.krateo.io
  resource:
    kind: RunnerGroup
    identifiers:
      - id
    additionalStatusFields:
      - org
    verbsDescription:
    #- action: findby
    #  method: GET
    #  path: /orgs/{org}/actions/runner-groups
    - action: get
      method: GET
      path: /orgs/{org}/actions/runner-groups/{id}
    - action: update
      method: PATCH
      path: /orgs/{org}/actions/runner-groups/{id}
    - action: create
      method: POST
      path: /orgs/{org}/actions/runner-groups
    - action: delete
      method: DELETE
      path: /orgs/{org}/actions/runner-groups/{id}
{{ end }}
