{{- if .Values.restdefinitions.teamrepo.enabled }}
kind: RestDefinition
apiVersion: swaggergen.krateo.io/v1alpha1
metadata:
  name: {{ .Release.Name }}-teamrepo
spec:
  oasPath: configmap://{{ .Release.Namespace }}/{{ .Release.Name }}-teamrepo/teamrepo.yaml
  resourceGroup: github.krateo.io
  resource: 
    kind: TeamRepo
    identifiers:
      - id 
      - name
      - full_name
      - permission
    verbsDescription:
    - action: create
      method: PUT
      path: /orgs/{org}/teams/{team_slug}/repos/{owner}/{repo}
    - action: delete
      method: DELETE
      path: /orgs/{org}/teams/{team_slug}/repos/{owner}/{repo}
    - action: get
      method: GET
      path: /teamrepository/orgs/{org}/teams/{team_slug}/repos/{owner}/{repo}
    - action: update
      method: PUT
      path: /orgs/{org}/teams/{team_slug}/repos/{owner}/{repo}
{{ end }}
