{{- if .Values.restdefinitions.workflow.enabled }}
kind: RestDefinition
apiVersion: swaggergen.krateo.io/v1alpha1
metadata:
  name: {{ .Release.Name }}-workflow
spec:
  oasPath: configmap://{{ .Release.Namespace }}/{{ .Release.Name }}-workflow/workflow.yaml
  resourceGroup: github.krateo.io
  resource: 
    kind: Workflow
    verbsDescription:
    - action: create
      method: POST
      path: /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches
{{ end }}
