apiVersion: github.kog.krateo.io/v1alpha1
kind: RunnerGroup
metadata:
  name: runner-test
  namespace: ghp
  annotations:
    krateo.io/connector-verbose: "true"
spec:
  authenticationRefs:
    bearerAuthRef: bearer-gh-ref
  name: runner-test-by-krateo
  org: krateoplatformops-test
  allows_public_repositories: false
  restricted_to_workflows: false
  #runners:  # List of runners IDs to add to the runner group.
  #  - 00000001
  #  - 00000002
  #selected_repository_ids:  # List of repository IDs that can access the runner group.
  #  - 1230000001
  #  - 1230000002
  #selected_workflows:  # List of workflows the runner group should be allowed to run, ignored unless `restricted_to_workflows` is set to `true`.
  #  - workflow-test-1
  #  - workflow-test-2
  #visibility: all # Visibility of the runner group by repositories. You can select all. private or selected repositories (`all`, `private`, or `selected`).
