---
openapi: 3.0.3
info:
  version: 1.1.4
  title: GitHub v3 REST API
  description: GitHub's v3 REST API.
  license:
    name: MIT
    url: https://spdx.org/licenses/MIT
  termsOfService: https://docs.github.com/articles/github-terms-of-service
  contact:
    name: Support
    url: https://support.github.com/contact?tags=dotcom-rest-api
  x-github-plan: api.github.com
servers:
- url: https://api.github.com
externalDocs:
  description: GitHub v3 REST API
  url: https://docs.github.com/rest/
paths:
  /repository/{owner}/{repo}/collaborators/{username}:
    post:
      servers:
        - url: {{ include "webServiceUrl" . }}
          description: Url used for a pod exposed with 8080 port exposed via clusterIP service
      summary: Add a repository collaborator
      description: Add a repository collaborator or invite a user to collaborate on a repository
      operationId: post-repo-collaborator
      parameters:
        - name: owner
          in: path
          description: Owner of the repository
          required: true
          schema:
            type: string
        - name: repo
          in: path
          description: Name of the repository
          required: true
          schema:
            type: string
        - name: username
          in: path
          description: Username of the collaborator to add
          required: true
          schema:
            type: string
      requestBody:
        description: Permission to grant to the collaborator
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/collaborator.Permission'
        required: true
      responses:
        "202":
          description: Invitation sent to user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/collaborator.Message'
        "204":
          description: User already collaborator
          content: {}
      x-codegen-request-body-name: permission
    delete:
      servers:
        - url: {{ include "webServiceUrl" . }}
          description: Url used for a pod exposed with 8080 port exposed via clusterIP service
      summary: Delete repository collaborator or cancel invitation
      description: Remove a collaborator from repository or cancel a pending invitation
      operationId: delete-repo-collaborator
      parameters:
        - name: owner
          in: path
          description: Owner of the repository
          required: true
          schema:
            type: string
        - name: repo
          in: path
          description: Name of the repository
          required: true
          schema:
            type: string
        - name: username
          in: path
          description: Username of the collaborator to remove
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Collaborator removed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/collaborator.Message'
        "202":
          description: Invitation cancelled successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/collaborator.Message'
        "404":
          description: User not found as collaborator or invitee
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/collaborator.Message'
    patch:
      servers:
        - url: {{ include "webServiceUrl" . }}
          description: Url used for a pod exposed with 8080 port exposed via clusterIP service
      summary: Update repository collaborator permission or invitation
      description: Update the permission of an existing collaborator or pending invitation
      operationId: patch-repo-collaborator
      parameters:
        - name: owner
          in: path
          description: Owner of the repository
          required: true
          schema:
            type: string
        - name: repo
          in: path
          description: Name of the repository
          required: true
          schema:
            type: string
        - name: username
          in: path
          description: Username of the collaborator
          required: true
          schema:
            type: string
      requestBody:
        description: New permission to set (`pull`, `push`, `admin`, `maintain`, `triage`)
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/collaborator.Permission'
        required: true
      responses:
        "200":
          description: Permission updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/collaborator.Message'
        "202":
          description: Invitation permission updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/collaborator.Message'
      x-codegen-request-body-name: permissions
  /repository/{owner}/{repo}/collaborators/{username}/permission:
    get:
      servers:
        - url: {{ include "webServiceUrl" . }}
          description: Url used for a pod exposed with 8080 port exposed via clusterIP service
      summary: Get the permission of a user in a repository
      description: Get the permission of a user in a repository
      operationId: get-repo-permission
      parameters:
        - name: owner
          in: path
          description: Owner of the repository
          required: true
          schema:
            type: string
        - name: repo
          in: path
          description: Name of the repository
          required: true
          schema:
            type: string
        - name: username
          in: path
          description: Username of the collaborator
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/collaborator.RepoPermissions'
components:
  securitySchemes:
    accessToken:
      type: http
      scheme: bearer
  schemas:
    collaborator.Message:
      type: object
      properties:
        message:
          type: string
    collaborator.Permission:
      type: object
      properties:
        permission:
          type: string
    collaborator.Permissions:
      type: object
      properties:
        admin:
          type: boolean
        maintain:
          type: boolean
        pull:
          type: boolean
        push:
          type: boolean
        triage:
          type: boolean
    collaborator.RepoPermissions:
      type: object
      properties:
        html_url:
          type: string
        id:
          type: integer
        message:
          type: string
        permission:
          type: string
        permissions:
          $ref: '#/components/schemas/collaborator.Permissions'
        role_name:
          type: string
        user:
          $ref: '#/components/schemas/collaborator.User'
    collaborator.User:
      type: object
      properties:
        avatar_url:
          type: string
        events_url:
          type: string
        followers_url:
          type: string
        following_url:
          type: string
        gists_url:
          type: string
        gravatar_id:
          type: string
        html_url:
          type: string
        id:
          type: integer
        login:
          type: string
        node_id:
          type: string
        organizations_url:
          type: string
        permissions:
          $ref: '#/components/schemas/collaborator.Permissions'
        received_events_url:
          type: string
        repos_url:
          type: string
        role_name:
          type: string
        site_admin:
          type: boolean
        starred_url:
          type: string
        subscriptions_url:
          type: string
        type:
          type: string
        url:
          type: string
        user_view_type:
          type: string
    