---
openapi: 3.0.3
info:
  version: 1.1.4
  title: GitHub v3 REST API
  description: GitHub's v3 REST API.
  license:
    name: MIT
    url: https://spdx.org/licenses/MIT
  termsOfService: https://docs.github.com/articles/github-terms-of-service
  contact:
    name: Support
    url: https://support.github.com/contact?tags=dotcom-rest-api
  x-github-plan: api.github.com
servers:
- url: https://api.github.com
externalDocs:
  description: GitHub v3 REST API
  url: https://docs.github.com/rest/
paths:
  "/repos/{owner}/{repo}/invitations":
    get:
      summary: List repository invitations
      description: When authenticating as a user with admin rights to a repository,
        this endpoint will list all currently open repository invitations.
      tags:
      - repos
      operationId: repos/list-invitations
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/rest/collaborators/invitations#list-repository-invitations
      parameters:
      - "$ref": "#/components/parameters/owner"
      - "$ref": "#/components/parameters/repo"
      - "$ref": "#/components/parameters/per-page"
      - "$ref": "#/components/parameters/page"
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/repository-invitation"
              examples:
                default:
                  "$ref": "#/components/examples/repository-invitation-items"
          headers:
            Link:
              "$ref": "#/components/headers/link"
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: true
        category: collaborators
        subcategory: invitations
  "/repos/{owner}/{repo}/invitations/{invitation_id}":
    patch:
      summary: Update a repository invitation
      description: ''
      tags:
      - repos
      operationId: repos/update-invitation
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/rest/collaborators/invitations#update-a-repository-invitation
      parameters:
      - "$ref": "#/components/parameters/owner"
      - "$ref": "#/components/parameters/repo"
      - "$ref": "#/components/parameters/invitation-id"
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                permissions:
                  type: string
                  description: The permissions that the associated user will have
                    on the repository. Valid values are `read`, `write`, `maintain`,
                    `triage`, and `admin`.
                  enum:
                  - read
                  - write
                  - maintain
                  - triage
                  - admin
            examples:
              default:
                summary: Example request body
                value:
                  permissions: write
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/repository-invitation"
              examples:
                default:
                  "$ref": "#/components/examples/repository-invitation"
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: true
        category: collaborators
        subcategory: invitations
    delete:
      summary: Delete a repository invitation
      description: ''
      tags:
      - repos
      operationId: repos/delete-invitation
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/rest/collaborators/invitations#delete-a-repository-invitation
      parameters:
      - "$ref": "#/components/parameters/owner"
      - "$ref": "#/components/parameters/repo"
      - "$ref": "#/components/parameters/invitation-id"
      responses:
        '204':
          description: Response
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: true
        category: collaborators
        subcategory: invitations
components:
  parameters:
    owner:
      name: owner
      in: path
      required: true
      description: The account owner of the repository. The name is not case sensitive.
      schema:
        type: string
    repo:
      name: repo
      in: path
      required: true
      description: The name of the repository. The name is not case sensitive.
      schema:
        type: string
    invitation-id:
      name: invitation_id
      in: path
      required: true
      description: The unique identifier of the repository invitation.
      schema:
        type: integer
    per-page:
      name: per_page
      in: query
      description: Results per page (max 100).
      schema:
        type: integer
        default: 30
    page:
      name: page
      in: query
      description: Page number of the results to fetch.
      schema:
        type: integer
  schemas:
    

  examples:
